export const cartTable = [
  { name: "Subtotal", price: 0.0 },
  { name: "Sales Tax", price: 0.0 },
  { name: "Shipping", price: 0.0 },
  { name: "Discount", price: 0.0 },
  { name: "Total", price: 0.0 },
  // Add more products here...
];

export const campaignData = {
  result: "SUCCESS",
  message: {
    execTime: null,
    memUsage: null,
    totalResults: 1,
    resultsPerPage: 25,
    page: 1,
    data: {
      "8": {
        campaignId: 8,
        dateCreated: "2021-12-15 18:23:09",
        campaignName: "Brow Charm Main Campaign",
        campaignType: "ECOMMERCE",
        currency: "USD",
        requireQA: 0,
        listSalesEntry: 0,
        captureOnShipment: 0,
        requireTOS: 0,
        eSignature: 0,
        campaignTOS: null,
        preauthOnly: 0,
        enableFraudPlugin: 0,
        insureShipId: 0,
        insureShipBillerId: null,
        insureShipLoadBalancerId: null,
        defaultShipProfileId: 5,
        externalCampaignId: null,
        qaPercent: 0,
        campaignCategoryId: 13,
        pinlessDebitRoute: 0,
        prPercent: 0,
        codOrders: 0,
        blockPrepaid: 0,
        blockDebit: 0,
        blockMastercard: 0,
        blockVisa: 0,
        disableExternalPayments: 0,
        disableRecycleBilling: 0,
        singleTransaction: 0,
        bundleFulfillment: 0,
        blockChargebackBlacklist: 0,
        couponMax: 1,
        visible: 1,
        isLocked: 0,
        taxServiceId: null,
        autoTax: 0,
        upsellWindow: null,
        maxBundleHours: 96,
        reOrderDays: null,
        currencySymbol: "$",
        currencyNumber: "840",
        defaultCouponCode: null,
        products: [
          {
            campaignProductId: 101,
            productName: "VIP Customer Benefits",
            productType: "UPSALE",
            price: "0.00",
            shippingPrice: "0.00",
            compareAtPrice: null,
            billerId: 2147483648,
            billerName: null,
            showToAffiliates: 1,
            useOfferMid: 1,
            loadBalancerId: null,
            loadBalancerName: null,
            billingCycleType: "RECURRING",
            finalBillingCycle: null,
            staggerFulfillments: 0,
            staggerIntervalCycles: null,
            cycle1_price: "0.00",
            cycle1_shipPrice: "0.00",
            cycle1_isShippable: 0,
            cycle1_billDelay: 30,
            cycle2_price: "34.71",
            cycle2_shipPrice: "0.00",
            cycle2_isShippable: 0,
            cycle2_billDelay: 30,
            cycle3_price: "34.71",
            cycle3_shipPrice: "0.00",
            cycle3_isShippable: 0,
            cycle3_billDelay: 30,
            trialEnabled: 0,
            trialType: null,
            trialAuthType: null,
            trialBillerId: null,
            trialBillerName: null,
            trialLoadBalancerId: null,
            trialLoadBalancerName: null,
            minOrderPrice: "0.00",
            maxOrderPrice: null,
            maxOrderQty: null,
            productId: 69,
            clientProductId: null,
            baseProductName: "VIP Customer Benefits",
            productSku: "vip-customer-benefits-getbrowcharm",
            productDescription: null,
            productCost: "0.00",
            shippingCost: null,
            weight: null,
            msrp: null,
            isVariantBundle: 0,
            bundleProductQty: null,
            productQty: 1,
            campaignProductQty: null,
            productCategoryId: null,
            productCategoryName: null,
            isProductCombo: null,
            fulfillmentCycleType: "RECURRING",
            fulfillmentHouseId: null,
            fulfillmentDelayHours: 1,
            clubPluginId: null,
            externalProductId: null,
            imageUrl: "https://images.konnektive.com/nymbus_llc/product69.png",
            stockQuantity: "0",
            allowStorePickup: null,
            productTags: null,
            variantDetailId: null,
            externalVariantDetailId: null,
            isEditable: 0,
            storefront: 1,
            taxServiceId: null,
            descriptor: null,
            fixedBillingDay: null,
            persistentRebillDay: 0,
            isPricePercent: 0,
            hasVariants: false,
            cycle1_productId: 69,
            cycle1_combinationId: 0,
            cycle2_productId: 69,
            cycle2_combinationId: 0,
            cycle3_productId: 69,
            cycle3_combinationId: 0,
            cycle4_price: "34.71",
            cycle4_shipPrice: "0.00",
            cycle4_isShippable: 0,
            cycle4_billDelay: 30,
            cycle4_productId: 69,
            cycle4_combinationId: 0,
            variants: [],
          },
        ],
        countries: [
          {
            countryName: "United States",
            countryCode: "US",
            continent: "NA",
            currencyCode: "USD",
            numericCode: "840",
          },
          {
            countryName: "Canada",
            countryCode: "CA",
            continent: "NA",
            currencyCode: "CAD",
            numericCode: "124",
          },
          {
            countryName: "Afghanistan",
            countryCode: "AF",
            continent: "AS",
            currencyCode: "AFN",
            numericCode: "004",
          },
          {
            countryName: "Aland  Islands",
            countryCode: "AX",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "004",
          },
          {
            countryName: "Albania",
            countryCode: "AL",
            continent: "EU",
            currencyCode: "ALL",
            numericCode: "008",
          },
          {
            countryName: "Algeria",
            countryCode: "DZ",
            continent: "AF",
            currencyCode: "DZD",
            numericCode: "012",
          },
          {
            countryName: "American Samoa",
            countryCode: "AS",
            continent: "NA",
            currencyCode: "USD",
            numericCode: "016",
          },
          {
            countryName: "Andorra",
            countryCode: "AD",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "020",
          },
          {
            countryName: "Angola",
            countryCode: "AO",
            continent: "AF",
            currencyCode: "AOA",
            numericCode: "024",
          },
          {
            countryName: "Anguilla",
            countryCode: "AI",
            continent: "NA",
            currencyCode: "ECD",
            numericCode: "660",
          },
          {
            countryName: "Antigua and Barbuda",
            countryCode: "AG",
            continent: "SA",
            currencyCode: "XCD",
            numericCode: "028",
          },
          {
            countryName: "Argentina",
            countryCode: "AR",
            continent: "SA",
            currencyCode: "ARS",
            numericCode: "032",
          },
          {
            countryName: "Armenia",
            countryCode: "AM",
            continent: "AS",
            currencyCode: "AMD",
            numericCode: "051",
          },
          {
            countryName: "Aruba",
            countryCode: "AW",
            continent: "SA",
            currencyCode: "AFL",
            numericCode: "533",
          },
          {
            countryName: "Australia",
            countryCode: "AU",
            continent: "AU",
            currencyCode: "AUD",
            numericCode: "036",
          },
          {
            countryName: "Austria",
            countryCode: "AT",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "040",
          },
          {
            countryName: "Azerbaijan",
            countryCode: "AZ",
            continent: "EU",
            currencyCode: "AZN",
            numericCode: "031",
          },
          {
            countryName: "Bahamas",
            countryCode: "BS",
            continent: "NA",
            currencyCode: "BSD",
            numericCode: "044",
          },
          {
            countryName: "Bahrain",
            countryCode: "BH",
            continent: "AS",
            currencyCode: "BHD",
            numericCode: "048",
          },
          {
            countryName: "Bangladesh",
            countryCode: "BD",
            continent: "AS",
            currencyCode: "BDT",
            numericCode: "050",
          },
          {
            countryName: "Barbados",
            countryCode: "BB",
            continent: "SA",
            currencyCode: "BBD",
            numericCode: "052",
          },
          {
            countryName: "Belarus",
            countryCode: "BY",
            continent: "EU",
            currencyCode: "BYR",
            numericCode: "112",
          },
          {
            countryName: "Belgium",
            countryCode: "BE",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "056",
          },
          {
            countryName: "Belize",
            countryCode: "BZ",
            continent: "SA",
            currencyCode: "BZD",
            numericCode: "084",
          },
          {
            countryName: "Benin",
            countryCode: "BJ",
            continent: "AF",
            currencyCode: "XOF",
            numericCode: "204",
          },
          {
            countryName: "Bermuda",
            countryCode: "BM",
            continent: "NA",
            currencyCode: "BMU",
            numericCode: "060",
          },
          {
            countryName: "Bhutan",
            countryCode: "BT",
            continent: "AS",
            currencyCode: "BTN",
            numericCode: "064",
          },
          {
            countryName: "Bolivia",
            countryCode: "BO",
            continent: "SA",
            currencyCode: "BOB",
            numericCode: "068",
          },
          {
            countryName: "Bosnia ",
            countryCode: "BA",
            continent: "EU",
            currencyCode: "BAM",
            numericCode: "070",
          },
          {
            countryName: "Botswana",
            countryCode: "BW",
            continent: "AF",
            currencyCode: "BWP",
            numericCode: "072",
          },
          {
            countryName: "Brazil",
            countryCode: "BR",
            continent: "SA",
            currencyCode: "BRL",
            numericCode: "076",
          },
          {
            countryName: "British Indian Ocean",
            countryCode: "IO",
            continent: "AS",
            currencyCode: "USD",
            numericCode: "086",
          },
          {
            countryName: "British Virgin Islands ",
            countryCode: "VG",
            continent: "NA",
            currencyCode: "USD",
            numericCode: "092",
          },
          {
            countryName: "Brunei Darussalam",
            countryCode: "BN",
            continent: "AS",
            currencyCode: "BND",
            numericCode: "096",
          },
          {
            countryName: "Bulgaria",
            countryCode: "BG",
            continent: "EU",
            currencyCode: "BGN",
            numericCode: "100",
          },
          {
            countryName: "Burkina Faso",
            countryCode: "BF",
            continent: "AF",
            currencyCode: "XOF",
            numericCode: "854",
          },
          {
            countryName: "Burundi",
            countryCode: "BI",
            continent: "AF",
            currencyCode: "BIF",
            numericCode: "108",
          },
          {
            countryName: "Cambodia",
            countryCode: "KH",
            continent: "AS",
            currencyCode: "KHR",
            numericCode: "116",
          },
          {
            countryName: "Cameroon",
            countryCode: "CM",
            continent: "AF",
            currencyCode: "XAF",
            numericCode: "120",
          },
          {
            countryName: "Cape Verde",
            countryCode: "CV",
            continent: "AF",
            currencyCode: "CVE",
            numericCode: "132",
          },
          {
            countryName: "Cayman Islands",
            countryCode: "KY",
            continent: "SA",
            currencyCode: "KYD",
            numericCode: "136",
          },
          {
            countryName: "Central African Republic",
            countryCode: "CF",
            continent: "AF",
            currencyCode: "XAF",
            numericCode: "140",
          },
          {
            countryName: "Chad",
            countryCode: "TD",
            continent: "AF",
            currencyCode: "XAF",
            numericCode: "148",
          },
          {
            countryName: "Chile",
            countryCode: "CL",
            continent: "SA",
            currencyCode: "CLP",
            numericCode: "152",
          },
          {
            countryName: "China",
            countryCode: "CN",
            continent: "AS",
            currencyCode: "CNY",
            numericCode: "156",
          },
          {
            countryName: "Christmas Island",
            countryCode: "CX",
            continent: "AS",
            currencyCode: "AUD",
            numericCode: "162",
          },
          {
            countryName: "Cocos ",
            countryCode: "CC",
            continent: "AS",
            currencyCode: "AUD",
            numericCode: "166",
          },
          {
            countryName: "Colombia",
            countryCode: "CO",
            continent: "SA",
            currencyCode: "COP",
            numericCode: "170",
          },
          {
            countryName: "Comoros",
            countryCode: "KM",
            continent: "AF",
            currencyCode: "KMF",
            numericCode: "174",
          },
          {
            countryName: "Congo",
            countryCode: "CG",
            continent: "AF",
            currencyCode: "XAF",
            numericCode: "178",
          },
          {
            countryName: "Congo (Democratic Republic of the)",
            countryCode: "CD",
            continent: "AF",
            currencyCode: null,
            numericCode: null,
          },
          {
            countryName: "Costa Rica",
            countryCode: "CR",
            continent: "SA",
            currencyCode: "CRC",
            numericCode: "188",
          },
          {
            countryName: "Cote D'Ivoire",
            countryCode: "CI",
            continent: "AF",
            currencyCode: "XOF",
            numericCode: "384",
          },
          {
            countryName: "Croatia",
            countryCode: "HR",
            continent: "EU",
            currencyCode: "HRK",
            numericCode: "191",
          },
          {
            countryName: "Cuba",
            countryCode: "CU",
            continent: "SA",
            currencyCode: "CUP",
            numericCode: "192",
          },
          {
            countryName: "Cyprus",
            countryCode: "CY",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "196",
          },
          {
            countryName: "Czech Republic",
            countryCode: "CZ",
            continent: "EU",
            currencyCode: "CZK",
            numericCode: "203",
          },
          {
            countryName: "Denmark",
            countryCode: "DK",
            continent: "EU",
            currencyCode: "DKK",
            numericCode: "208",
          },
          {
            countryName: "Djibouti",
            countryCode: "DJ",
            continent: "AF",
            currencyCode: "DJF",
            numericCode: "262",
          },
          {
            countryName: "Dominica",
            countryCode: "DM",
            continent: "SA",
            currencyCode: "XCD",
            numericCode: "212",
          },
          {
            countryName: "Dominican Republic",
            countryCode: "DO",
            continent: "SA",
            currencyCode: "DOP",
            numericCode: "214",
          },
          {
            countryName: "Ecuador",
            countryCode: "EC",
            continent: "SA",
            currencyCode: "USD",
            numericCode: "218",
          },
          {
            countryName: "Egypt",
            countryCode: "EG",
            continent: "AF",
            currencyCode: "EGP",
            numericCode: "818",
          },
          {
            countryName: "El Salvador",
            countryCode: "SV",
            continent: "SA",
            currencyCode: "USD",
            numericCode: "222",
          },
          {
            countryName: "Equatorial Guinea",
            countryCode: "GQ",
            continent: "AF",
            currencyCode: "XAF",
            numericCode: "226",
          },
          {
            countryName: "Eritrea",
            countryCode: "ER",
            continent: "AF",
            currencyCode: "ERN",
            numericCode: "232",
          },
          {
            countryName: "Estonia",
            countryCode: "EE",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "233",
          },
          {
            countryName: "Ethiopia",
            countryCode: "ET",
            continent: "AF",
            currencyCode: "ETB",
            numericCode: "231",
          },
          {
            countryName: "Falkland Islands",
            countryCode: "FK",
            continent: "SA",
            currencyCode: "FKP",
            numericCode: "238",
          },
          {
            countryName: "Faroe Islands",
            countryCode: "FO",
            continent: "EU",
            currencyCode: "FOK",
            numericCode: "234",
          },
          {
            countryName: "Fiji",
            countryCode: "FJ",
            continent: "AU",
            currencyCode: "FJD",
            numericCode: "242",
          },
          {
            countryName: "Finland",
            countryCode: "FI",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "246",
          },
          {
            countryName: "France",
            countryCode: "FR",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "250",
          },
          {
            countryName: "French Guiana",
            countryCode: "GF",
            continent: "SA",
            currencyCode: "EUR",
            numericCode: "254",
          },
          {
            countryName: "French Polynesia",
            countryCode: "PF",
            continent: "EU",
            currencyCode: "XPF",
            numericCode: "258",
          },
          {
            countryName: "French Southern Territories",
            countryCode: "TF",
            continent: "AF",
            currencyCode: "EUR",
            numericCode: "260",
          },
          {
            countryName: "Gabon",
            countryCode: "GA",
            continent: "AF",
            currencyCode: "XAF",
            numericCode: "266",
          },
          {
            countryName: "Gambia",
            countryCode: "GM",
            continent: "AF",
            currencyCode: "GMD",
            numericCode: "270",
          },
          {
            countryName: "Georgia",
            countryCode: "GE",
            continent: "AF",
            currencyCode: "GEL",
            numericCode: "268",
          },
          {
            countryName: "Germany",
            countryCode: "DE",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "276",
          },
          {
            countryName: "Ghana",
            countryCode: "GH",
            continent: "AF",
            currencyCode: "GHS",
            numericCode: "288",
          },
          {
            countryName: "Gibraltar",
            countryCode: "GI",
            continent: "EU",
            currencyCode: "GIP",
            numericCode: "292",
          },
          {
            countryName: "Greece",
            countryCode: "GR",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "300",
          },
          {
            countryName: "Greenland",
            countryCode: "GL",
            continent: "EU",
            currencyCode: "DKK",
            numericCode: "304",
          },
          {
            countryName: "Grenada",
            countryCode: "GD",
            continent: "SA",
            currencyCode: "XCD",
            numericCode: "308",
          },
          {
            countryName: "Guadeloupe",
            countryCode: "GP",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "312",
          },
          {
            countryName: "Guatemala",
            countryCode: "GT",
            continent: "SA",
            currencyCode: "GTQ",
            numericCode: "320",
          },
          {
            countryName: "Guinea",
            countryCode: "GN",
            continent: "AF",
            currencyCode: "GNF",
            numericCode: "324",
          },
          {
            countryName: "Guinea-bissau",
            countryCode: "GW",
            continent: "AF",
            currencyCode: "XOF",
            numericCode: "624",
          },
          {
            countryName: "Guyana",
            countryCode: "GY",
            continent: "SA",
            currencyCode: "GYD",
            numericCode: "328",
          },
          {
            countryName: "Haiti",
            countryCode: "HT",
            continent: "SA",
            currencyCode: "HTG",
            numericCode: "332",
          },
          {
            countryName: "Honduras",
            countryCode: "HN",
            continent: "SA",
            currencyCode: "HNL",
            numericCode: "340",
          },
          {
            countryName: "Hong Kong",
            countryCode: "HK",
            continent: "AS",
            currencyCode: "HKD",
            numericCode: "344",
          },
          {
            countryName: "Hungary",
            countryCode: "HU",
            continent: "EU",
            currencyCode: "HUF",
            numericCode: "348",
          },
          {
            countryName: "Iceland",
            countryCode: "IS",
            continent: "EU",
            currencyCode: "ISK",
            numericCode: "352",
          },
          {
            countryName: "India",
            countryCode: "IN",
            continent: "AS",
            currencyCode: "INR",
            numericCode: "356",
          },
          {
            countryName: "Indonesia",
            countryCode: "ID",
            continent: "AS",
            currencyCode: "IDR",
            numericCode: "360",
          },
          {
            countryName: "Iran (Islamic Republic of)",
            countryCode: "IR",
            continent: "AS",
            currencyCode: "IRR",
            numericCode: "364",
          },
          {
            countryName: "Iraq",
            countryCode: "IQ",
            continent: "AS",
            currencyCode: "IQD",
            numericCode: "368",
          },
          {
            countryName: "Ireland",
            countryCode: "IE",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "372",
          },
          {
            countryName: "Isle of Man",
            countryCode: "IM",
            continent: "EU",
            currencyCode: "GBP",
            numericCode: "833",
          },
          {
            countryName: "Israel",
            countryCode: "IL",
            continent: "AS",
            currencyCode: "ILS",
            numericCode: "376",
          },
          {
            countryName: "Italy",
            countryCode: "IT",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "380",
          },
          {
            countryName: "Jamaica",
            countryCode: "JM",
            continent: "SA",
            currencyCode: "JMD",
            numericCode: "388",
          },
          {
            countryName: "Japan",
            countryCode: "JP",
            continent: "AS",
            currencyCode: "JPY",
            numericCode: "392",
          },
          {
            countryName: "Jersey",
            countryCode: "JE",
            continent: "EU",
            currencyCode: "GBP",
            numericCode: "832",
          },
          {
            countryName: "Jordan ",
            countryCode: "JO",
            continent: "AS",
            currencyCode: "JOD",
            numericCode: "400",
          },
          {
            countryName: "Kazakhstan",
            countryCode: "KZ",
            continent: "AS",
            currencyCode: "KZT",
            numericCode: "398",
          },
          {
            countryName: "Kenya",
            countryCode: "KE",
            continent: "AF",
            currencyCode: "KES",
            numericCode: "404",
          },
          {
            countryName: "Kiribati",
            countryCode: "KI",
            continent: "AU",
            currencyCode: "AUD",
            numericCode: "296",
          },
          {
            countryName: "Korea, North",
            countryCode: "KP",
            continent: "AS",
            currencyCode: "KPW",
            numericCode: "408",
          },
          {
            countryName: "Korea, South",
            countryCode: "KR",
            continent: "AS",
            currencyCode: "KRW",
            numericCode: "410",
          },
          {
            countryName: "Kuwait",
            countryCode: "KW",
            continent: "AS",
            currencyCode: "KWD",
            numericCode: "414",
          },
          {
            countryName: "Kyrgyzstan",
            countryCode: "KG",
            continent: "AS",
            currencyCode: "KGS",
            numericCode: "417",
          },
          {
            countryName: "Lao People's Democratic Republic",
            countryCode: "LA",
            continent: "AS",
            currencyCode: "LAK",
            numericCode: "418",
          },
          {
            countryName: "Latvia",
            countryCode: "LV",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "428",
          },
          {
            countryName: "Lebanon",
            countryCode: "LB",
            continent: "AS",
            currencyCode: "LBP",
            numericCode: "422",
          },
          {
            countryName: "Lesotho",
            countryCode: "LS",
            continent: "AF",
            currencyCode: "LSL",
            numericCode: "426",
          },
          {
            countryName: "Liberia",
            countryCode: "LR",
            continent: "AF",
            currencyCode: "LRD",
            numericCode: "430",
          },
          {
            countryName: "Libyan Arab Jamahiriya",
            countryCode: "LY",
            continent: "AF",
            currencyCode: "LYD",
            numericCode: "434",
          },
          {
            countryName: "Liechtenstein",
            countryCode: "LI",
            continent: "EU",
            currencyCode: "CHF",
            numericCode: "438",
          },
          {
            countryName: "Lithuania",
            countryCode: "LT",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "440",
          },
          {
            countryName: "Luxembourg",
            countryCode: "LU",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "442",
          },
          {
            countryName: "Macedonia",
            countryCode: "MK",
            continent: "EU",
            currencyCode: "MKD",
            numericCode: "807",
          },
          {
            countryName: "Madagascar",
            countryCode: "MG",
            continent: "AF",
            currencyCode: "MGA",
            numericCode: "450",
          },
          {
            countryName: "Malawi",
            countryCode: "MW",
            continent: "AF",
            currencyCode: "MWK",
            numericCode: "454",
          },
          {
            countryName: "Malaysia",
            countryCode: "MY",
            continent: "AS",
            currencyCode: "MYR",
            numericCode: "458",
          },
          {
            countryName: "Maldives",
            countryCode: "MV",
            continent: "AS",
            currencyCode: "MVR",
            numericCode: "462",
          },
          {
            countryName: "Mali",
            countryCode: "ML",
            continent: "AF",
            currencyCode: "XOF",
            numericCode: "466",
          },
          {
            countryName: "Malta ",
            countryCode: "MT",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "470",
          },
          {
            countryName: "Marshall Islands",
            countryCode: "MH",
            continent: "AS",
            currencyCode: "USD",
            numericCode: "584",
          },
          {
            countryName: "Martinique",
            countryCode: "MQ",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "474",
          },
          {
            countryName: "Mauritania",
            countryCode: "MR",
            continent: "AF",
            currencyCode: "MRO",
            numericCode: "478",
          },
          {
            countryName: "Mauritius",
            countryCode: "MU",
            continent: "AF",
            currencyCode: "MUR",
            numericCode: "480",
          },
          {
            countryName: "Mayotte ",
            countryCode: "YT",
            continent: "AF",
            currencyCode: "EUR",
            numericCode: "175",
          },
          {
            countryName: "Mexico",
            countryCode: "MX",
            continent: "SA",
            currencyCode: "MXN",
            numericCode: "484",
          },
          {
            countryName: "Micronesia, Federated States of",
            countryCode: "FM",
            continent: "AS",
            currencyCode: "USD",
            numericCode: "583",
          },
          {
            countryName: "Moldova",
            countryCode: "MD",
            continent: "EU",
            currencyCode: "MDL",
            numericCode: "498",
          },
          {
            countryName: "Monaco",
            countryCode: "MC",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: null,
          },
          {
            countryName: "Mongolia",
            countryCode: "MN",
            continent: "AS",
            currencyCode: "MNT",
            numericCode: "496",
          },
          {
            countryName: "Montserrat ",
            countryCode: "MS",
            continent: "NA",
            currencyCode: "XCD",
            numericCode: "500",
          },
          {
            countryName: "Morocco",
            countryCode: "MA",
            continent: "AF",
            currencyCode: "MAD",
            numericCode: "504",
          },
          {
            countryName: "Mozambique",
            countryCode: "MZ",
            continent: "AF",
            currencyCode: "MZN",
            numericCode: "508",
          },
          {
            countryName: "Myanmar",
            countryCode: "MM",
            continent: "AS",
            currencyCode: "MMK",
            numericCode: "104",
          },
          {
            countryName: "Namibia",
            countryCode: "NA",
            continent: "AF",
            currencyCode: "NAD",
            numericCode: "516",
          },
          {
            countryName: "Nauru",
            countryCode: "NR",
            continent: "AS",
            currencyCode: "AUD",
            numericCode: "520",
          },
          {
            countryName: "Nepal",
            countryCode: "NP",
            continent: "AS",
            currencyCode: "NPR",
            numericCode: "524",
          },
          {
            countryName: "Netherlands",
            countryCode: "NL",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "528",
          },
          {
            countryName: "Netherlands Antilles",
            countryCode: "AN",
            continent: "NA",
            currencyCode: "ANG",
            numericCode: "530",
          },
          {
            countryName: "New Zealand",
            countryCode: "NZ",
            continent: "AU",
            currencyCode: "NZD",
            numericCode: "554",
          },
          {
            countryName: "Nicaragua",
            countryCode: "NI",
            continent: "SA",
            currencyCode: "NIO",
            numericCode: "558",
          },
          {
            countryName: "Niger",
            countryCode: "NE",
            continent: "AF",
            currencyCode: "XOF",
            numericCode: "562",
          },
          {
            countryName: "Nigeria",
            countryCode: "NG",
            continent: "AF",
            currencyCode: "NGN",
            numericCode: "566",
          },
          {
            countryName: "Northern Mariana Islands",
            countryCode: "MP",
            continent: "NA",
            currencyCode: "USD",
            numericCode: "580",
          },
          {
            countryName: "Norway",
            countryCode: "NO",
            continent: "EU",
            currencyCode: "NOK",
            numericCode: "578",
          },
          {
            countryName: "Oman ",
            countryCode: "OM",
            continent: "AS",
            currencyCode: "OMR",
            numericCode: "512",
          },
          {
            countryName: "Pakistan",
            countryCode: "PK",
            continent: "AS",
            currencyCode: "PKR",
            numericCode: "586",
          },
          {
            countryName: "Palau",
            countryCode: "PW",
            continent: "AU",
            currencyCode: "USD",
            numericCode: "585",
          },
          {
            countryName: "Panama",
            countryCode: "PA",
            continent: "SA",
            currencyCode: "PAB",
            numericCode: "591",
          },
          {
            countryName: "Papua New Guinea",
            countryCode: "PG",
            continent: "AU",
            currencyCode: "PGK",
            numericCode: "598",
          },
          {
            countryName: "Paraguay",
            countryCode: "PY",
            continent: "SA",
            currencyCode: "PYG",
            numericCode: "600",
          },
          {
            countryName: "Peru",
            countryCode: "PE",
            continent: "SA",
            currencyCode: "PEN",
            numericCode: "604",
          },
          {
            countryName: "Philippines",
            countryCode: "PH",
            continent: "AS",
            currencyCode: "PHP",
            numericCode: "608",
          },
          {
            countryName: "Poland",
            countryCode: "PL",
            continent: "EU",
            currencyCode: "PLN",
            numericCode: "616",
          },
          {
            countryName: "Portugal",
            countryCode: "PT",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "620",
          },
          {
            countryName: "Puerto Rico",
            countryCode: "PR",
            continent: "NA",
            currencyCode: "USD",
            numericCode: "630",
          },
          {
            countryName: "Qatar",
            countryCode: "QA",
            continent: "AS",
            currencyCode: "QAR",
            numericCode: "634",
          },
          {
            countryName: "Réunion",
            countryCode: "RE",
            continent: "AF",
            currencyCode: "EUR",
            numericCode: "638",
          },
          {
            countryName: "Romania",
            countryCode: "RO",
            continent: "EU",
            currencyCode: "RON",
            numericCode: null,
          },
          {
            countryName: "Russian Federation",
            countryCode: "RU",
            continent: "AS",
            currencyCode: "RUB",
            numericCode: "643",
          },
          {
            countryName: "Rwanda",
            countryCode: "RW",
            continent: "AF",
            currencyCode: "RWF",
            numericCode: "646",
          },
          {
            countryName: "Saint Kitts and Nevis",
            countryCode: "KN",
            continent: "SA",
            currencyCode: "XCD",
            numericCode: "659",
          },
          {
            countryName: "Saint Lucia",
            countryCode: "LC",
            continent: "NA",
            currencyCode: "XCD",
            numericCode: "662",
          },
          {
            countryName: "Saint Pierre and Miquelon",
            countryCode: "PM",
            continent: "NA",
            currencyCode: "EUR",
            numericCode: "666",
          },
          {
            countryName: "Saint Vincent and the Grenadines",
            countryCode: "VC",
            continent: "SA",
            currencyCode: "XCD",
            numericCode: "670",
          },
          {
            countryName: "Samoa",
            countryCode: "WS",
            continent: "AU",
            currencyCode: "WST",
            numericCode: "882",
          },
          {
            countryName: "San Marino",
            countryCode: "SM",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "674",
          },
          {
            countryName: "Sao Tome and Principe",
            countryCode: "ST",
            continent: "AF",
            currencyCode: "STD",
            numericCode: "678",
          },
          {
            countryName: "Saudi Arabia",
            countryCode: "SA",
            continent: "AS",
            currencyCode: "SAR",
            numericCode: "682",
          },
          {
            countryName: "Senegal",
            countryCode: "SN",
            continent: "AF",
            currencyCode: "XOF",
            numericCode: "686",
          },
          {
            countryName: "Serbia",
            countryCode: "RS",
            continent: "EU",
            currencyCode: null,
            numericCode: "688",
          },
          {
            countryName: "Seychelles",
            countryCode: "SC",
            continent: "AF",
            currencyCode: "SCR",
            numericCode: "690",
          },
          {
            countryName: "Sierra Leone",
            countryCode: "SL",
            continent: "AF",
            currencyCode: "SLL",
            numericCode: "694",
          },
          {
            countryName: "Singapore",
            countryCode: "SG",
            continent: "AS",
            currencyCode: "SGD",
            numericCode: "702",
          },
          {
            countryName: "Slovak Republic",
            countryCode: "SK",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "703",
          },
          {
            countryName: "Slovenia",
            countryCode: "SI",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "705",
          },
          {
            countryName: "Solomon Islands",
            countryCode: "SB",
            continent: "AU",
            currencyCode: "SBD",
            numericCode: "090",
          },
          {
            countryName: "Somalia",
            countryCode: "SO",
            continent: "AF",
            currencyCode: "SOS",
            numericCode: "706",
          },
          {
            countryName: "South Africa",
            countryCode: "ZA",
            continent: "AF",
            currencyCode: "ZAR",
            numericCode: "710",
          },
          {
            countryName: "Spain",
            countryCode: "ES",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "724",
          },
          {
            countryName: "Sri Lanka",
            countryCode: "LK",
            continent: "AS",
            currencyCode: null,
            numericCode: null,
          },
          {
            countryName: "St. Helena",
            countryCode: "SH",
            continent: "SA",
            currencyCode: "SHP",
            numericCode: null,
          },
          {
            countryName: "Sudan ",
            countryCode: "SD",
            continent: "AF",
            currencyCode: "SDG",
            numericCode: "736",
          },
          {
            countryName: "Suriname",
            countryCode: "SR",
            continent: "SA",
            currencyCode: "SRD",
            numericCode: "740",
          },
          {
            countryName: "Svalbard and Jan Mayen Islands",
            countryCode: "SJ",
            continent: "EU",
            currencyCode: "NOK",
            numericCode: "744",
          },
          {
            countryName: "Swaziland",
            countryCode: "SZ",
            continent: "AF",
            currencyCode: "SZL",
            numericCode: "748",
          },
          {
            countryName: "Sweden",
            countryCode: "SE",
            continent: "EU",
            currencyCode: "SEK",
            numericCode: "752",
          },
          {
            countryName: "Switzerland",
            countryCode: "CH",
            continent: "EU",
            currencyCode: "CHF",
            numericCode: "756",
          },
          {
            countryName: "Syrian Arab Republic",
            countryCode: "SY",
            continent: "AS",
            currencyCode: "SYP",
            numericCode: "760",
          },
          {
            countryName: "Taiwan",
            countryCode: "TW",
            continent: "AS",
            currencyCode: "TWD",
            numericCode: "158",
          },
          {
            countryName: "Tajikistan",
            countryCode: "TJ",
            continent: "AS",
            currencyCode: "TJS",
            numericCode: "762",
          },
          {
            countryName: "Tanzania, United Republic of",
            countryCode: "TZ",
            continent: "AF",
            currencyCode: "TZS",
            numericCode: "834",
          },
          {
            countryName: "Thailand",
            countryCode: "TH",
            continent: "AS",
            currencyCode: "THB",
            numericCode: "764",
          },
          {
            countryName: "Togo",
            countryCode: "TG",
            continent: "AF",
            currencyCode: "XOF",
            numericCode: "768",
          },
          {
            countryName: "Tonga",
            countryCode: "TO",
            continent: "AU",
            currencyCode: "TOP",
            numericCode: "776",
          },
          {
            countryName: "Trinidad and Tobago",
            countryCode: "TT",
            continent: "SA",
            currencyCode: "TTD",
            numericCode: "780",
          },
          {
            countryName: "Tunisia",
            countryCode: "TN",
            continent: "AF",
            currencyCode: "TND",
            numericCode: "788",
          },
          {
            countryName: "Turkey",
            countryCode: "TR",
            continent: "AS",
            currencyCode: "TRY",
            numericCode: "792",
          },
          {
            countryName: "Turkmenistan",
            countryCode: "TM",
            continent: "AS",
            currencyCode: "TMT",
            numericCode: "795",
          },
          {
            countryName: "Turks and Caicos Islands ",
            countryCode: "TC",
            continent: "NA",
            currencyCode: "USD",
            numericCode: "796",
          },
          {
            countryName: "Tuvalu",
            countryCode: "TV",
            continent: "AU",
            currencyCode: "AUD",
            numericCode: "798",
          },
          {
            countryName: "Uganda",
            countryCode: "UG",
            continent: "AF",
            currencyCode: "UGX",
            numericCode: "800",
          },
          {
            countryName: "Ukraine",
            countryCode: "UA",
            continent: "AS",
            currencyCode: "UAH",
            numericCode: "804",
          },
          {
            countryName: "United Arab Emirates",
            countryCode: "AE",
            continent: "AS",
            currencyCode: "AED",
            numericCode: "784",
          },
          {
            countryName: "United Kingdom",
            countryCode: "GB",
            continent: "EU",
            currencyCode: "GBP",
            numericCode: "826",
          },
          {
            countryName: "Uruguay",
            countryCode: "UY",
            continent: "SA",
            currencyCode: "UYU",
            numericCode: "858",
          },
          {
            countryName: "Uzbekistan",
            countryCode: "UZ",
            continent: "AS",
            currencyCode: "UZS",
            numericCode: "860",
          },
          {
            countryName: "Vanuatu",
            countryCode: "VU",
            continent: "AU",
            currencyCode: "VUV",
            numericCode: "548",
          },
          {
            countryName: "Vatican City State (Holy See)",
            countryCode: "VA",
            continent: "EU",
            currencyCode: "EUR",
            numericCode: "336",
          },
          {
            countryName: "Venezuela",
            countryCode: "VE",
            continent: "SA",
            currencyCode: "VEF",
            numericCode: "862",
          },
          {
            countryName: "Viet Nam",
            countryCode: "VN",
            continent: "AS",
            currencyCode: "VND",
            numericCode: "704",
          },
          {
            countryName: "Virgin Islands, US",
            countryCode: "VI",
            continent: "NA",
            currencyCode: "USD",
            numericCode: "850",
          },
          {
            countryName: "Western Sahara",
            countryCode: "EH",
            continent: "AF",
            currencyCode: "MAD",
            numericCode: "732",
          },
          {
            countryName: "Yemen ",
            countryCode: "YE",
            continent: "AS",
            currencyCode: "YER",
            numericCode: "887",
          },
          {
            countryName: "Zambia",
            countryCode: "ZM",
            continent: "AF",
            currencyCode: "ZMK",
            numericCode: "894",
          },
          {
            countryName: "Zimbabwe",
            countryCode: "ZW",
            continent: "AF",
            currencyCode: "ZWL",
            numericCode: "716",
          },
        ],
        currencies: [
          {
            currencyCode: "USD",
            symbolAlign: "LEFT",
            includeShipping: 0,
            isComma: 0,
            decimals: 2,
            rounding: null,
            currencyFee: "0.00",
            sendToGateway: 1,
            currencySymbol: "$",
            currencyNumber: "840",
            currencyName: "US Dollar",
          },
        ],
        taxes: [
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "AZ",
            stateName: "Arizona",
            taxRate: "0.056000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "AR",
            stateName: "Arkansas",
            taxRate: "0.065000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "CA",
            stateName: "California",
            taxRate: "0.072500",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "CT",
            stateName: "Connecticut",
            taxRate: "0.063500",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "FL",
            stateName: "Florida",
            taxRate: "0.060000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "GA",
            stateName: "Georgia",
            taxRate: "0.040000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "IL",
            stateName: "Illinois",
            taxRate: "0.062500",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "IN",
            stateName: "Indiana",
            taxRate: "0.070000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "IA",
            stateName: "Iowa",
            taxRate: "0.060000",
            isVat: 0,
            excludeRebills: 0,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "KS",
            stateName: "Kansas",
            taxRate: "0.065000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "LA",
            stateName: "Louisiana",
            taxRate: "0.044500",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "MA",
            stateName: "Massachusetts",
            taxRate: "0.060000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "MN",
            stateName: "Minnesota",
            taxRate: "0.068800",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "NV",
            stateName: "Nevada",
            taxRate: "0.046000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "NJ",
            stateName: "New Jersey",
            taxRate: "0.066300",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "NY",
            stateName: "New York",
            taxRate: "0.070000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "OK",
            stateName: "Oklahoma",
            taxRate: "0.045000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "PA",
            stateName: "Pennsylvania",
            taxRate: "0.060000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "SC",
            stateName: "South Carolina",
            taxRate: "0.060000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "TX",
            stateName: "Texas",
            taxRate: "0.080000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "VA",
            stateName: "Virginia",
            taxRate: "0.043000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "WA",
            stateName: "Washington",
            taxRate: "0.065000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "CO",
            stateName: "Colorado",
            taxRate: "0.029000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "DC",
            stateName: "District of Columbia",
            taxRate: "0.060000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "HI",
            stateName: "Hawaii",
            taxRate: "0.040000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "MD",
            stateName: "Maryland",
            taxRate: "0.060000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "MI",
            stateName: "Michigan",
            taxRate: "0.060000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "MO",
            stateName: "Missouri",
            taxRate: "0.042300",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "NE",
            stateName: "Nebraska",
            taxRate: "0.055000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "OH",
            stateName: "Ohio",
            taxRate: "0.057500",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "RI",
            stateName: "Rhode Island",
            taxRate: "0.070000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "UT",
            stateName: "Utah",
            taxRate: "0.047000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "VT",
            stateName: "Vermont",
            taxRate: "0.060000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "WV",
            stateName: "West Virginia",
            taxRate: "0.060000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "WI",
            stateName: "Wisconsin",
            taxRate: "0.050000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "WY",
            stateName: "Wyoming",
            taxRate: "0.040000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 0,
          },
          {
            countryCode: "US",
            countryName: "United States",
            stateCode: "TN",
            stateName: "Tennessee",
            taxRate: "0.070000",
            isVat: 0,
            excludeRebills: 1,
            applyToShipping: 1,
          },
        ],
        coupons: [
          {
            couponCode: "SAVE10",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "SAVE15",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "SALE10",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "FLASH20",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "BROWCHARM10",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "GRATITUDE10",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "BCMOM20",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "XMASVIP",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "XMASGIFT",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "PARTYTIME",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "GF209GJ48EOW02",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "SMSBE2154692",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "SEARCHOFF",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "WELCOME20",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "WELCOME10",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "OFFCART",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "BFCART",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "WELCOMEBF",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "SALE20",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "PEG10",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "PEG15",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "PEG20",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "FREESHIP",
            applyTo: "SHIPPING",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "1.0000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: null,
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "3493527042",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "7345537022",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.5000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "8128569503",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "9301087047",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "2627794049",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.3000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "3489072123",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.4000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "9076189724",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "7028803487",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "4518032907",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "4317862198",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "6948983142",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.5000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "4285677114",
            applyTo: "SHIPPING",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "1.0000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "7400044012",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "VIPFREE",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "1.0000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "1229,1254",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "NOVIP",
            applyTo: "BASE_PRICE",
            discountType: "FLAT",
            defaultCoupon: 0,
            discountPrice: "0.00",
            discountPerc: null,
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455,1229,1254,1255",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "VIP10",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "PERFECT15",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1229,1254,1280",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "BROW15",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "LABOR15",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "SHOPNOW10",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1229,1254,1280",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "FALL4",
            applyTo: "BASE_PRICE",
            discountType: "FLAT",
            defaultCoupon: 0,
            discountPrice: "4.00",
            discountPerc: null,
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1229,1254,1280",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "REDISCOVER",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "CELEBRATE10",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "SAVE8",
            applyTo: "BASE_PRICE",
            discountType: "FLAT",
            defaultCoupon: 0,
            discountPrice: "8.00",
            discountPerc: null,
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "REFILL20",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "BOGO50",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.5000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,112,113,114,455,1254,1280",
            rules: [
              {
                ruleType: "BUY_X_GET_Y_QTY",
                startValue: "1.00",
                endValue: "99999.00",
                product: "455",
                productQty: "1",
                discount: "50.00",
              },
              {
                ruleType: "BUY_X_GET_Y_QTY",
                startValue: "1.00",
                endValue: "99999.00",
                product: "1254",
                productQty: "1",
                discount: "50.00",
              },
              {
                ruleType: "BUY_X_GET_Y_QTY",
                startValue: "1.00",
                endValue: "99999.00",
                product: "1280",
                productQty: "1",
                discount: "50.00",
              },
              {
                ruleType: "BUY_X_GET_Y_QTY",
                startValue: "1.00",
                endValue: "99999.00",
                product: "114",
                productQty: "1",
                discount: "50.00",
              },
              {
                ruleType: "BUY_X_GET_Y_QTY",
                startValue: "1.00",
                endValue: "99999.00",
                product: "113",
                productQty: "1",
                discount: "50.00",
              },
              {
                ruleType: "BUY_X_GET_Y_QTY",
                startValue: "1.00",
                endValue: "99999.00",
                product: "109",
                productQty: "1",
                discount: "50.00",
              },
              {
                ruleType: "BUY_X_GET_Y_QTY",
                startValue: "1.00",
                endValue: "99999.00",
                product: "110",
                productQty: "1",
                discount: "50.00",
              },
              {
                ruleType: "BUY_X_GET_Y_QTY",
                startValue: "1.00",
                endValue: "99999.00",
                product: "112",
                productQty: "1",
                discount: "50.00",
              },
              {
                ruleType: "BUY_X_GET_Y_QTY",
                startValue: "1.00",
                endValue: "99999.00",
                product: "108",
                productQty: "1",
                discount: "50.00",
              },
            ],
            oncePerOrder: 0,
          },
          {
            couponCode: "BESTDEAL",
            applyTo: "BASE_PRICE",
            discountType: "FLAT",
            defaultCoupon: 0,
            discountPrice: "8.00",
            discountPerc: null,
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1254",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "HOLIDAY25",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1254",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "HOLIDAYSALE",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1254",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "CRAZYGOOD",
            applyTo: "BASE_PRICE",
            discountType: "FLAT",
            defaultCoupon: 0,
            discountPrice: "8.00",
            discountPerc: null,
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1254,1280",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "TEXT25",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "PERFECTPAIR",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "BROWLOVE10",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1254",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "MOREBROWS",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.1500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1254",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "20LOVE",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "LOVE20",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "SPRING20",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "20SPRING",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "CELEBRATE20",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1254",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "20CELEBRATE",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110,1254",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "SUMMER20",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "20SUMMER",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2000",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId: "108,109,110",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "25LABOR",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId:
              "106,107,108,109,110,450,451,1229,1254,1280,1330,1331,1332,1333,1334,1335,2775,2776,4254,4261",
            rules: [],
            oncePerOrder: 0,
          },
          {
            couponCode: "LABOR25",
            applyTo: "BASE_PRICE",
            discountType: "PERCENT",
            defaultCoupon: 0,
            discountPrice: null,
            discountPerc: "0.2500",
            isRecurring: 0,
            isAutomatic: 0,
            recurringDiscountPrice: null,
            recurringDiscountPerc: null,
            campaignProductId:
              "106,107,108,109,110,450,451,1229,1254,1280,1330,1331,1332,1333,1334,1335,2775,2776,4254,4261",
            rules: [],
            oncePerOrder: 0,
          },
        ],
        shipProfiles: [
          {
            shipProfileId: 5,
            profileName: "Standard Shipping (7-10 days)",
            shipCarrier: "USPS",
            shipMethod: null,
            shipRefCode: "standard",
            highestShipPriceOnly: 0,
            isUpcharge: 0,
            applyEntireOrder: 1,
            freeShipThreshold: null,
            skipUpsell: 0,
            includeCoupons: 0,
            rules: [
              {
                region: "",
                state: "",
                productTypeSelect: "PRODUCTS",
                productCategoryId: "",
                campaignProductId: "",
                productTags: "",
                valueThreshold: "0.00",
                weightThreshold: "0.000",
                maxWeightThreshold: "0.000",
                itemCountThreshold: "",
                ruleCarrier: "",
                ruleMethod: "",
                zoneId: "",
                shipPrice: "4.95",
                shipCost: "0.00",
              },
            ],
          },
        ],
        zones: [],
        storePickup: [],
        customFields: [
          {
            fieldName: "funnel",
            fieldType: "STR",
          },
          {
            fieldName: "chckfunnel",
            fieldType: "STR",
          },
        ],
      },
    },
    params: null,
    errors: null,
    sortBy: "campaignId",
    sortDir: 1,
    queryArgs: {
      page: 1,
      sortDir: 1,
      resultsPerPage: 25,
      sortBy: "campaignId",
      campaignId: "8",
      campaignProductId: "101",
      checkoutchampapp: false,
      visible: true,
      dateRangeType: "dateCreated",
    },
  },
};
